---

- name: Test sshd configuration and restart
  command: sshd -t
  notify: [ 'Restart sshd' ]

- name: Restart sshd
  service:
    name: "{{'sshd' if ansible_os_family|lower == 'redhat' else 'ssh' }}"
    state: 'restarted'
